name: Android CI

on: 
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Set up JDK 11
          uses: actions/setup-jaca@v1
          with:
            java-version: 11

        - name: Build with Gradle
          rub: ./gradlew assembleRelease

        - name: Upload APK
          uses: actions/upload-artifact@v2
          with:
            name: app-release.apk
            path: app/build/outputs/apk/release/app-release.apk